apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  airflow.cfg: |
    [core]
    executor = CeleryExecutor
    load_examples = False
    dags_folder = /opt/airflow/dags

    [database]
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@mlops-postgres:5432/airflow

    [celery]
    broker_url = redis://redis:6379/0
    result_backend = db+postgresql://airflow:airflow@mlops-postgres:5432/airflow
    worker_concurrency = 2

    [webserver]
    base_url = http://localhost:8080
    web_server_host = 0.0.0.0
    web_server_port = 8080

    [scheduler]
    min_file_process_interval = 30

    [logging]
    base_log_folder = /opt/airflow/logs
    logging_level = INFO 