apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        {{- if .Values.gitSync.enabled }}
        - name: git-sync
          image: "{{ .Values.gitSync.image.repository }}:{{ .Values.gitSync.image.tag }}"
          imagePullPolicy: {{ .Values.gitSync.image.pullPolicy }}
          env:
            - name: GIT_SYNC_REPO
              value: {{ .Values.gitSync.repository }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.gitSync.branch }}
            - name: GIT_SYNC_ROOT
              value: /git
            - name: GIT_SYNC_DEST
              value: repo
            - name: GIT_SYNC_WAIT
              value: "{{ .Values.gitSync.wait }}"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "{{ .Values.gitSync.maxFailures }}"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
          {{- if .Values.gitSync.sshKeySecret }}
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: /etc/git-secret/ssh
          {{- end }}
          {{- if .Values.gitSync.credentialsSecret }}
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitSync.credentialsSecret }}
                  key: username
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitSync.credentialsSecret }}
                  key: password
          {{- end }}
          volumeMounts:
            - name: dags-volume
              mountPath: /git
          {{- if .Values.gitSync.sshKeySecret }}
            - name: git-secret
              mountPath: /etc/git-secret/ssh
              subPath: ssh
          {{- end }}
        {{- end }}
        - name: airflow-scheduler
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - airflow
            - scheduler
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: RAW_DB_CONN
              value: postgresql+psycopg2://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: CLEAN_DB_CONN
              value: postgresql+psycopg2://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: DB_GET_DATA
              value: http://fastapi:8989/data
            - name: DB_FORMAT_DATA
              value: http://fastapi:8989/reset
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
              {{- if .Values.gitSync.enabled }}
              subPath: repo{{- if .Values.gitSync.subPath }}/{{ .Values.gitSync.subPath }}{{- end }}
              {{- end }}
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: plugins-volume
              mountPath: /opt/airflow/plugins
            - name: tmp-dir
              mountPath: /opt/airflow/dags/tmp
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
      volumes:
        - name: dags-volume
          {{- if and .Values.persistence.dags.enabled .Values.gitSync.enabled }}
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: plugins-volume
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}
        - name: airflow-config
          configMap:
            name: airflow-config
        {{- if and .Values.gitSync.enabled .Values.gitSync.sshKeySecret }}
        - name: git-secret
          secret:
            secretName: {{ .Values.gitSync.sshKeySecret }}
            defaultMode: 0400
        {{- end }} 