apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      containers:
        {{- if .Values.gitSync.enabled }}
        - name: git-sync
          image: {{ .Values.gitSync.image.repository }}:{{ .Values.gitSync.image.tag }}
          imagePullPolicy: {{ .Values.gitSync.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              /git-sync \
                --repo={{ .Values.gitSync.repository }} \
                --branch={{ .Values.gitSync.branch }} \
                --depth=1 \
                --one-time=false \
                --root=/tmp/git \
                --dest=repo \
                --wait=60 &
              
              while true; do
                if [ -d "/tmp/git/repo/dags" ]; then
                  rm -rf /opt/airflow/dags/*
                  cp -r /tmp/git/repo/dags/* /opt/airflow/dags/ 2>/dev/null || true
                fi
                sleep 60
              done
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
          resources:
            {{- toYaml .Values.gitSync.resources | nindent 12 }}
        {{- end }}
        - name: airflow-triggerer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["airflow", "triggerer"]
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
          resources:
            {{- toYaml .Values.triggerer.resources | nindent 12 }}
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: plugins-volume
              mountPath: /opt/airflow/plugins
            - name: tmp-dir
              mountPath: /opt/airflow/dags/tmp
      volumes:
        - name: dags-volume
          emptyDir: {}
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: plugins-volume
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}