apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  access-key: {{ .Values.minio.credentials.accessKey | b64enc }}
  secret-key: {{ .Values.minio.credentials.secretKey | b64enc }} 