image:
  repository: blutenherz/mlflow-mlops
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

initContainer:
  image:
    repository: postgres
    tag: "13"
    pullPolicy: IfNotPresent

database:
  host: mlops-postgres
  port: 5432
  name: mlflow
  user: airflow
  password: airflow

minio:
  endpoint: http://minio:9000
  bucket: mlflows3
  secretName: minio-credentials

resources:
  requests:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

probes:
  readiness:
    path: /
    port: 5000
    initialDelaySeconds: 10
    periodSeconds: 5
  liveness:
    path: /
    port: 5000
    initialDelaySeconds: 30
    periodSeconds: 15 