image:
  repository: prom/prometheus
  tag: v2.52.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

config:
  scrapeInterval: 10s
  evaluationInterval: 10s
  targets:
    fastapi:
      host: fastapi
      port: 8989
      path: /metrics

  kubernetesDiscovery:
    enabled: true
    podScraping:
      enabled: true 