apiVersion: v1
kind: Service
metadata:
  name: mlops-postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mlops-postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.postgresql.port }} 