apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 