apiVersion: v2
name: mlops-platform
description: Plataforma MLOps completa con Airflow, MLflow, FastAPI y más
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: secrets
    version: 0.1.0
    repository: "file://./secrets"
    condition: secrets.enabled
  - name: postgres
    version: 0.1.0
    repository: "file://./postgres"
    condition: postgres.enabled
  - name: redis
    version: 0.1.0
    repository: "file://./redis"
    condition: redis.enabled
  - name: minio
    version: 0.1.0
    repository: "file://./minio"
    condition: minio.enabled
  - name: mlflow
    version: 0.1.0
    repository: "file://./mlflow"
    condition: mlflow.enabled
  - name: airflow
    version: 0.1.0
    repository: "file://./airflow"
    condition: airflow.enabled
  - name: fastapi
    version: 0.1.0
    repository: "file://./fastapi"
    condition: fastapi.enabled
  - name: prometheus
    version: 0.1.0
    repository: "file://./prometheus"
    condition: prometheus.enabled
  - name: grafana
    version: 0.1.0
    repository: "file://./grafana"
    condition: grafana.enabled
  - name: streamlit
    version: 0.1.0
    repository: "file://./streamlit"
    condition: streamlit.enabled 