apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mlflow
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: http 