apiVersion: v1
kind: Secret
metadata:
  name: mlops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jucroada/ProyectoFinal_MLOps_PUJ.git