apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- app.yaml

# Si necesitas personalizar la configuración de Argo CD, puedes agregar patches aquí
# patches:
# - path: patches/argocd-cm-patch.yaml
#   target:
#     kind: ConfigMap
#     name: argocd-cm