apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: {{ .Values.service.type }}
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
    - name: console
      protocol: TCP
      port: {{ .Values.service.ports.console.port }}
      targetPort: {{ .Values.service.ports.console.targetPort }} 